### ISSUE TITLE
NPE in EmailFormatterInbound prevents all mail from being read

### ISSUE THREAD

**Issue by turt2live** [kamax-io/matrix-appservice-email#27]
```
java.lang.NullPointerException: null
        at io.kamax.matrix.bridge.email.model.email.EmailFormatterInbound.get(EmailFormatterInbound.java:126) ~[classes!/:na]
        at io.kamax.matrix.bridge.email.model.email.EmailManager.lambda$afterPropertiesSet$0(EmailManager.java:57) ~[classes!/:na]
        at io.kamax.matrix.bridge.email.model.email.EmailFetcher.lambda$connect$0(EmailFetcher.java:137) ~[classes!/:na]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_192]

```

**Comment by maxidorius** [comment]
Fixed with 677342a45ba06494e49dc44dbbddaec00a77a097
